name             'java_properties'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures java_properties'
long_description 'Installs/Configures java_properties'
version          '0.1.0'
